### ISSUE TITLE
Update NPM to point at the repo with the implentation's codebase

### ISSUE THREAD

**Issue by aljones15** [digitalbazaar/did-method-key#32]
https://www.npmjs.com/package/did-method-key

The HomePage on npm still points at:
http://github.com/digitalbazaar/did-method-key

that should probably be updated to the newer spec repo.

The repo link should probably point here:
https://github.com/digitalbazaar/did-method-key-js

When using the npm page for `did-method-key` it's not immediately apparent where the code base and/or spec are.

**Comment by dlongley** [comment]
Closing as the link goes to the right place now.
